name: Build and Publish Docker Image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      # We do only publish if workflow is triggered by a tag push and we are not using act for local testing
      SHOULD_PUBLISH: ${{ startsWith(github.ref, 'refs/tags/') && github.actor != 'nektos/act' }}
      # We need fallback if run locally with act, because it does not support github.event.repository.name
      REPO_NAME: "ros2_fundamentals_nodes"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject Slug Variables
        run: |
          echo "IMAGE_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "IMAGE_NAME=$( [ -z "${{ github.event.repository.name }}" ] && echo "${{ env.REPO_NAME }}" || echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]' )" >> $GITHUB_ENV

      - name: Validate tag format
        if: env.SHOULD_PUBLISH == 'true'
        run: |
          TAG="${GITHUB_REF_NAME}"
          if [[ ! "$TAG" =~ ^v-?[0-9]+\.[0-9]+(\.[0-9]+)*$ ]]; then
            echo "Invalid tag: $TAG"
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: env.SHOULD_PUBLISH == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/Dockerfile
          push: ${{ env.SHOULD_PUBLISH == 'true' }}
          tags: |
            ghcr.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          build-args: |
            USER_NAME=ros
            USER_PASSWORD=ros
          cache-from: ${{ env.SHOULD_PUBLISH == 'true' && 'type=gha' || '' }}
          cache-to: ${{ env.SHOULD_PUBLISH == 'true' && 'type=gha,mode=max' || '' }}